version: '3.3'
services:
  bot:
    container_name: "vfs_tracking_bot"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
    - ./app:/home/app
    - ./data:/home/data